[user]
name = "Derik Evangelista"
email = "derik@syntasso.io"  # override per-repo with jj config --repo

[ui]
diff-editor = ":builtin"
merge-editor = "nvim"
pager = "delta"

[merge-tools.delta]
program = "delta"

[aliases]
tug  = ["git", "fetch"]
sync = ["git", "push", "--all"]
push = ["git", "push"]
l    = ["log", "--limit", "10"]
ll   = ["log"]
d    = ["diff"]
s    = ["status"]
n    = ["new"]
c    = ["commit"]
sq   = ["squash"]
desc = ["describe"]
b    = ["bookmark"]
